### ISSUE TITLE
Consider https only

### ISSUE THREAD

**Issue by nothingismagick** [VanVan/ipfsProxyHTTP#2]
A non encrypted version of the page is automatically resolved when https:// is not specified, and the example suggests using http:

![cff1f1e8-8f69-4128-8e7b-d103a711b425](https://user-images.githubusercontent.com/35242872/38467227-7124bdac-3b35-11e8-8306-e06202e3788d.jpeg)

With https specified:
![aebe82e8-79e4-486b-b6da-e1b57148ef9f](https://user-images.githubusercontent.com/35242872/38467177-e3d8cc04-3b34-11e8-8f57-3d156f4601b6.jpeg)

**Comment by VanVan** [comment]
You are right, I added 2 commits to redirect http request to https.
It is now HTTPS only.
