### ISSUE TITLE
Expiration of the certificat of ipns.co

### ISSUE THREAD

**Issue by Kcchouette** [VanVan/ipfsProxyHTTP#8]
> Websites prove their identity via certificates, which are valid for a set time period. The certificate for ipns.co expired on 4/24/2020.
 
> Error code: SEC_ERROR_EXPIRED_CERTIFICATE

Cheers

**Comment by VanVan** [comment]
Problem solved, a restart of a docker instance on one of the servers reloaded the original certificates
