### ISSUE TITLE
adding CORS * support with javascript fetch

### ISSUE THREAD

**Issue by chisNaN** [VanVan/ipfsProxyHTTP#9]
Hello
thanks for your implementation
the speed difference is clearly visible
nevertheless i cannot fetch from crossdomain without cors error restriction

```js
const o = await(await fetch('https://ipns.co/QmYwAPJzv5CZsnA625s3Xf2nemtYgPpHdWEz79ojWnPbdG/readme')).text()
```

**Comment by chisNaN** [comment]
Impossible request.
Because every nodes should comply to this

**Comment by VanVan** [comment]
Perhaps the solution could be to maintain two separate node lists to respond with the appropriate list according to the HTTP request transmitted

**Comment by chisNaN** [comment]
Good idea.
if you can put an optional param for making priority to node having cors enabled

**Comment by VanVan** [comment]
The next question would be whether there is a list of nodes with cors enabled

**Comment by chisNaN** [comment]
for instance i know infura has cors* enabled but it should be dynamically check on the fly
